In [10]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [11]:
user = "postgres"
password = "vimaljue73"
host = "localhost"
port = 5432
database = "Grizzley_DB"

def get_connection():
    engine = create_engine(
        f"postgresql://{user}:{password}@{host}:{port}/{database}"
    )
    return engine

if __name__ == "__main__":

    try:
        engine = get_connection()
        print(f"Connection to the {host} for user {user} created successfully.")

    except Exception as ex:
        print("Connection could not be made due to the following error:\n", ex)

Connection to the localhost for user postgres created successfully.

In [79]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

tables = pd.read_sql(query, engine)
tables

          table_name
0       declarations
1           projects
2  projects_computed
3      subscriptions
4              tasks
5     tasks_computed
6              teams
7              users

In [61]:
def table_profile(table_name):
    df = pd.read_sql_table(table_name, con=engine)
    
    print(f"Table: {table_name}")
    print(f"Shape: {df.shape}")
    print("\nColumns:")
    
    for column in df.columns:
        print(f"  - {column}: {df[column].dtype}")

In [64]:
table_profile("users")

Table: users
Shape: (20556, 4)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - deleted_at: datetime64[ns, UTC]
  - team_id: object

In [65]:
table_profile("teams")

Table: teams
Shape: (2838, 3)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - deleted_at: datetime64[ns, UTC]

In [66]:
table_profile("projects")

Table: projects
Shape: (71792, 3)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - team_id: object

In [67]:
table_profile("projects_computed")

Table: projects_computed
Shape: (61962, 5)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - team_id: object
  - planned_duration: object
  - elapsed_duration: object

In [68]:
table_profile("tasks")

Table: tasks
Shape: (717470, 5)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - is_container: object
  - parent_id: object
  - project_id: object

In [69]:
table_profile("tasks_computed")

Table: tasks_computed
Shape: (628466, 7)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - is_container: object
  - parent_id: object
  - project_id: object
  - planned_duration: object
  - elapsed_duration: object

In [70]:
table_profile("declarations")

Table: declarations
Shape: (4446669, 7)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - date: datetime64[ns]
  - durations: int64
  - source: object
  - user_id: object
  - task_id: object

In [71]:
table_profile("subscriptions")

Table: subscriptions
Shape: (2838, 7)

Columns:
  - team_id: object
  - subscribe_at: datetime64[ns, UTC]
  - disabled_at: datetime64[ns, UTC]
  - status: object
  - offer: object
  - trial_start_at: datetime64[ns, UTC]
  - trial_end_at: datetime64[ns, UTC]

In [47]:
query = """
SELECT *
FROM users
LIMIT 5
"""

users_head = pd.read_sql(query, engine)
users_head

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00:00,2024-08-18 00:00:00.189885+00:00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00:00,2024-08-25 00:00:00.079552+00:00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.884420+00:00,NaT,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00:00,NaT,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00:00,NaT,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [48]:
query = """
SELECT *
FROM teams
LIMIT 5
"""

teams_head = pd.read_sql(query, engine)
teams_head

,id,created_at,deleted_at
0,0dae6fc0-5e50-40f5-a563-9ff3a924acc7,2023-04-19 09:53:26.653538+00:00,2024-07-23 00:00:00.080325+00:00
1,a09fdecc-9cb5-45bf-ac0f-82407ff0520e,2023-12-24 03:04:41.369719+00:00,2024-07-23 00:00:00.080325+00:00
2,15a5021a-4ca8-4058-93fc-d48eb288e262,2023-12-28 12:59:15.086754+00:00,2024-07-27 00:00:00.086003+00:00
3,b0acbb97-79c6-4009-a5cd-bed4f8fe3515,2024-02-23 12:23:14.626192+00:00,2024-08-22 00:00:00.108485+00:00
4,9d4ee2e9-0701-493b-ad36-a1c28b121ce4,2024-09-07 07:37:41.322453+00:00,NaT

In [50]:
query = """
SELECT *
FROM projects
LIMIT 5
"""

projects_head = pd.read_sql(query, engine)
projects_head

,id,created_at,team_id
0,036ce646-3e35-4184-b13f-5f9f77b2a2bc,2024-02-07 06:08:30.869191+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
1,bcd4f818-a23a-4816-8b39-568cdd13c24e,2024-02-07 06:11:51.849856+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
2,1ee9281f-8fa1-4508-bcc7-0c541a519960,2024-02-07 06:12:15.748188+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
3,d96a67e4-2e35-4baf-a281-306f47a986ec,2023-11-15 19:56:45.089798+00:00,6227700f-b4c6-4465-b771-5081a8789a87
4,2fa1365c-f5a8-4557-a3ad-6ebfeae7ca97,2024-01-29 11:48:04.224718+00:00,504b8a66-fe1a-42e7-bad9-d026c3640ba2

In [51]:
query = """
SELECT *
FROM projects_computed
LIMIT 5
"""

projects_computed_head = pd.read_sql(query, engine)
projects_computed_head

,id,created_at,team_id,planned_duration,elapsed_duration
0,a5d934fe-b9d2-4020-ae8c-f684c7b73d79,2024-02-21 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,0s
1,b446cbed-f3ec-4677-ba01-5de1b89796d2,2024-02-21 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,3h30m0s
2,806abfdf-3328-42e5-98f2-5c59b2c0870b,2024-02-24 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,6h0m0s
3,22797936-97ef-497e-8aec-e58c2ca542a2,2024-02-22 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,2h0m0s
4,3f95efc1-5edb-40ca-a76a-f35bd7abdb56,2024-02-21 18:30:00+00:00,eab347af-e533-41aa-99cd-02a2750d2b6a,0s,3h0m0s

In [52]:
query = """
SELECT *
FROM tasks
LIMIT 5
"""

tasks_head = pd.read_sql(query, engine)
tasks_head

,id,created_at,is_container,parent_id,project_id
0,1ea825ce-97cf-4852-9288-0d81cf937391,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
1,ae179aa8-ebdf-457d-a86d-2af4d9f7b1e8,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
2,d8f19281-267d-4544-bf5e-6d24cdfe5320,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
3,ee4ba0a4-843c-4364-83c6-b548a6cb6ec7,2022-02-01 18:20:42.558161+00:00,f,ae9b3630-a2f4-4684-94f0-0ae7a65d27e8,b206bff4-6ebc-4b80-8b07-740d91be1007
4,be57f933-ca3d-4d14-a317-04ee78c042cc,2022-02-01 18:20:42.558161+00:00,f,ae9b3630-a2f4-4684-94f0-0ae7a65d27e8,b206bff4-6ebc-4b80-8b07-740d91be1007

In [53]:
query = """
SELECT *
FROM tasks_computed
LIMIT 5
"""

tasks_computed_head = pd.read_sql(query, engine)
tasks_computed_head

,id,created_at,is_container,parent_id,project_id,planned_duration,elapsed_duration
0,e33ae6c4-bdae-47f0-b3b5-c640c0915a3b,2024-02-21 18:30:00+00:00,false,None,a5d934fe-b9d2-4020-ae8c-f684c7b73d79,0s,0s
1,7351af54-a08f-42d2-b00c-b012cd810912,2024-02-21 18:30:00+00:00,false,None,b446cbed-f3ec-4677-ba01-5de1b89796d2,0s,3h30m0s
2,b916baeb-85d6-4a19-a90c-5cbeb62bc6f9,2024-02-24 18:30:00+00:00,false,None,806abfdf-3328-42e5-98f2-5c59b2c0870b,0s,6h0m0s
3,b2b4b40c-a543-4a93-bdc0-ec89fd923e99,2024-02-24 18:30:00+00:00,false,None,806abfdf-3328-42e5-98f2-5c59b2c0870b,0s,0s
4,eae6977b-3b82-4279-ac37-26d0a886650f,2024-02-22 18:30:00+00:00,false,None,22797936-97ef-497e-8aec-e58c2ca542a2,0s,2h0m0s

In [54]:
query = """
SELECT *
FROM declarations
LIMIT 5
"""

declarations_head = pd.read_sql(query, engine)
declarations_head

,id,created_at,date,durations,source,user_id,task_id
0,d0959001-d0b5-4db1-9060-8784ce18a45e,2023-07-20 16:27:27.418890+00:00,2023-07-20,8100000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,fcb25935-fa19-4729-88bb-6c6517da33f3
1,1f673cc8-af4b-479f-b1b1-d10d8f556455,2023-07-20 16:19:09.100997+00:00,2023-07-20,9000000000000,app,8525b67f-c5d4-494b-b010-f645bece73f4,26b908f6-1771-4da7-9b2e-fb9066af06fb
2,61a838e8-499e-4031-99f3-4bc7b4edd7e8,2023-07-20 16:27:35.834489+00:00,2023-07-20,5400000000000,app,355b940b-b7c2-46ae-9aae-059098688fee,3ce2459d-1441-4bbd-aa14-601f795806d4
3,2e8e7807-723a-433c-a4e1-06dfaebc24a5,2023-07-20 16:27:48.537053+00:00,2023-07-17,2700000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,e215bb42-903b-43c7-bfa4-39aa90d5584c
4,d745827f-9cfc-42c6-996d-0eb52f5d52dc,2023-07-20 16:27:51.462235+00:00,2023-07-20,2700000000000,app,20544542-8f93-440a-bd6b-4b4a61d7e3de,3ce2459d-1441-4bbd-aa14-601f795806d4

In [55]:
query = """
SELECT *
FROM subscriptions
LIMIT 5
"""

subscriptions_head = pd.read_sql(query, engine)
subscriptions_head

,team_id,subscribe_at,disabled_at,status,offer,trial_start_at,trial_end_at
0,40fbd3a5-a26f-40a0-9442-97f463846bfb,NaT,2024-09-16 17:42:15.404460+00:00,disabled,budget,2024-09-16 17:39:00.137959+00:00,2024-09-30 17:39:00.137959+00:00
1,76eed2db-c452-4e19-98ae-60b5cf99b46b,2024-05-27 14:31:51+00:00,NaT,active,budget,2024-05-12 21:31:11.178486+00:00,2024-05-26 21:31:11.178486+00:00
2,88592354-0ddb-4be7-95bf-14d0e5f47e70,NaT,2024-09-21 01:00:01.414810+00:00,disabled,budget,2024-09-06 13:29:42.567109+00:00,2024-09-20 13:29:42.567109+00:00
3,c9af2120-1b74-4ebb-8009-8b9224d4dace,2024-02-15 12:37:39+00:00,NaT,active,budget,2020-03-29 12:49:40.985137+00:00,2020-04-29 12:49:40.985137+00:00
4,6e894a69-4062-4a43-85f9-ed57ec0a01e8,NaT,2024-06-24 01:00:01.148573+00:00,disabled,budget,2024-06-09 12:28:16.371489+00:00,2024-06-23 12:28:16.371489+00:00

In [90]:
user_df = pd.read_sql_table("users", con=engine)

user_df['team_id'].value_counts()

team_id
cad594d3-e120-4e64-88ba-02d755643bbc    1621
492236e8-866f-40b6-9450-55fe3dc37631     420
a1e7b8bb-34f0-4e86-89cd-f941f179e337     222
1761ef97-c3c9-41a5-ae0f-156f63138c50     221
99726867-5377-40e2-a614-e1aead83244f     208
                                        ...
1571330d-d1da-49ca-b500-e692847b9f86       2
310bbcee-4cb1-4110-a78f-d84ed54ac96d       1
cdc2319b-8b71-486c-b959-5b28bfbfd278       1
065bd86f-7aa7-4827-92d9-e75f42923884       1
c52a1d5e-8606-4c84-aaa2-45b429ad3756       1
Name: count, Length: 2838, dtype: int64