In [4]:
import numpy as np
import pandas as pd

In [16]:
declarations = pd.read_csv("../Dataset/declarations.csv")
projects_computed = pd.read_csv("../Dataset/projects_computed.csv")
projects = pd.read_csv("../Dataset/projects.csv")
subscriptions = pd.read_csv("../Dataset/subscriptions.csv")
tasks_computed = pd.read_csv("../Dataset/tasks_computed.csv")
tasks = pd.read_csv("../Dataset/tasks.csv")
teams = pd.read_csv("../Dataset/teams.csv")
users = pd.read_csv("../Dataset/users.csv")

In [44]:
print('Database Overview:')

print('--'*70)
print('Table Name: projects_computed')
print(f'Shape: {projects_computed.shape}')
print(f'Columns: {projects_computed.columns.tolist()}')
print('--'*70)

print('Table Name: projects')
print(f'Shape: {projects.shape}')
print(f'Columns: {projects.columns.tolist()}')
print('--'*70)

print('Table Name: subscriptions')
print(f'Shape: {subscriptions.shape}')
print(f'Columns: {subscriptions.columns.tolist()}')
print('--'*70)

print('Table Name: tasks_computed')
print(f'Shape: {tasks_computed.shape}')
print(f'Columns: {tasks_computed.columns.tolist()}')
print('--'*70)

print('Table Name: tasks')
print(f'Shape: {tasks.shape}')
print(f'Columns: {tasks.columns.tolist()}')
print('--'*70)

print('Table Name: teams')
print(f'Shape: {teams.shape}')
print(f'Columns: {teams.columns.tolist()}')
print('--'*70)

print('Table Name: users')
print(f'Shape: {users.shape}')
print(f'Columns: {users.columns.tolist()}')
print('--'*70)

Database Overview:
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: projects_computed
Shape: (61962, 5)
Columns: ['id', 'created_at', 'team_id', 'planned_duration', 'elapsed_duration']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: projects
Shape: (71792, 3)
Columns: ['id', 'created_at', 'team_id']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: subscriptions
Shape: (2838, 7)
Columns: ['team_id', 'subscribe_at', 'disabled_at', 'status', 'offer', 'trial_start_at', 'trial_end_at']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: tasks_computed
Shape: (628466, 7)
Columns: ['id', 'created_at', 'is_container', 'parent_id', 'project_id', 'planned_duration', 'elapsed_duration']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: tasks
Shape: (717470, 5)
Columns: ['id', 'created_at', 'is_container', 'parent_id', 'project_id']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: teams
Shape: (2838, 3)
Columns: ['id', 'created_at', 'deleted_at']
--------------------------------------------------------------------------------------------------------------------------------------------
Table Name: users
Shape: (20556, 4)
Columns: ['id', 'created_at', 'deleted_at', 'team_id']
--------------------------------------------------------------------------------------------------------------------------------------------

In [59]:
declarations.head()

,id,created_at,date,duration,source,user_id,task_id
0,d0959001-d0b5-4db1-9060-8784ce18a45e,2023-07-20 16:27:27.41889+00,2023-07-20,8100000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,fcb25935-fa19-4729-88bb-6c6517da33f3
1,1f673cc8-af4b-479f-b1b1-d10d8f556455,2023-07-20 16:19:09.100997+00,2023-07-20,9000000000000,app,8525b67f-c5d4-494b-b010-f645bece73f4,26b908f6-1771-4da7-9b2e-fb9066af06fb
2,61a838e8-499e-4031-99f3-4bc7b4edd7e8,2023-07-20 16:27:35.834489+00,2023-07-20,5400000000000,app,355b940b-b7c2-46ae-9aae-059098688fee,3ce2459d-1441-4bbd-aa14-601f795806d4
3,2e8e7807-723a-433c-a4e1-06dfaebc24a5,2023-07-20 16:27:48.537053+00,2023-07-17,2700000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,e215bb42-903b-43c7-bfa4-39aa90d5584c
4,d745827f-9cfc-42c6-996d-0eb52f5d52dc,2023-07-20 16:27:51.462235+00,2023-07-20,2700000000000,app,20544542-8f93-440a-bd6b-4b4a61d7e3de,3ce2459d-1441-4bbd-aa14-601f795806d4

In [60]:
declarations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4446669 entries, 0 to 4446668
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   id          object
 1   created_at  object
 2   date        object
 3   duration    int64
 4   source      object
 5   user_id     object
 6   task_id     object
dtypes: int64(1), object(6)
memory usage: 237.5+ MB

In [61]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2838 entries, 0 to 2837
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   team_id         2838 non-null   object
 1   subscribe_at    590 non-null    object
 2   disabled_at     2531 non-null   object
 3   status          2838 non-null   object
 4   offer           2838 non-null   object
 5   trial_start_at  2838 non-null   object
 6   trial_end_at    2838 non-null   object
dtypes: object(7)
memory usage: 155.3+ KB

In [62]:
subscriptions.head()

,team_id,subscribe_at,disabled_at,status,offer,trial_start_at,trial_end_at
0,40fbd3a5-a26f-40a0-9442-97f463846bfb,NaN,2024-09-16 17:42:15.40446+00,disabled,budget,2024-09-16 17:39:00.137959+00,2024-09-30 17:39:00.137959+00
1,76eed2db-c452-4e19-98ae-60b5cf99b46b,2024-05-27 14:31:51+00,NaN,active,budget,2024-05-12 21:31:11.178486+00,2024-05-26 21:31:11.178486+00
2,88592354-0ddb-4be7-95bf-14d0e5f47e70,NaN,2024-09-21 01:00:01.41481+00,disabled,budget,2024-09-06 13:29:42.567109+00,2024-09-20 13:29:42.567109+00
3,c9af2120-1b74-4ebb-8009-8b9224d4dace,2024-02-15 12:37:39+00,NaN,active,budget,2020-03-29 12:49:40.985137+00,2020-04-29 12:49:40.985137+00
4,6e894a69-4062-4a43-85f9-ed57ec0a01e8,NaN,2024-06-24 01:00:01.148573+00,disabled,budget,2024-06-09 12:28:16.371489+00,2024-06-23 12:28:16.371489+00