In [2]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [3]:
user = "postgres"
password = "vimaljue73"
host = "localhost"
port = 5432
database = "Grizzley_DB"

def get_connection():
    engine = create_engine(
        f"postgresql://{user}:{password}@{host}:{port}/{database}"
    )
    return engine

if __name__ == "__main__":

    try:
        engine = get_connection()
        print(f"Connection to the {host} for user {user} created successfully.")

    except Exception as ex:
        print("Connection could not be made due to the following error:\n", ex)

Connection to the localhost for user postgres created successfully.

In [4]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

tables = pd.read_sql(query, engine)
tables

          table_name
0       declarations
1           projects
2  projects_computed
3      subscriptions
4              tasks
5     tasks_computed
6              teams
7              users

In [5]:
def table_profile(table_name):

    # Row count
    row_count = pd.read_sql(
        f'SELECT COUNT(*) AS row_count FROM "{table_name}"',
        engine
    ).iloc[0, 0]

    # Only load 5 rows for pandas dtype detection
    sample = pd.read_sql(
        f'SELECT * FROM "{table_name}" LIMIT 5',
        engine
    )

    print(f"Table: {table_name}")
    print(f"Shape: ({row_count:,}, {len(sample.columns)})")

    print("\nColumns:")
    for column in sample.columns:
        print(f"  - {column}: {sample[column].dtype}")

In [6]:
table_profile("users")

Table: users
Shape: (20,556, 4)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - deleted_at: datetime64[ns, UTC]
  - team_id: object

In [7]:
table_profile("teams")

Table: teams
Shape: (2,838, 3)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - deleted_at: datetime64[ns, UTC]

In [8]:
table_profile("projects")

Table: projects
Shape: (71,792, 3)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - team_id: object

In [9]:
table_profile("projects_computed")

Table: projects_computed
Shape: (61,962, 5)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - team_id: object
  - planned_duration: object
  - elapsed_duration: object

In [10]:
table_profile("tasks")

Table: tasks
Shape: (717,470, 5)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - is_container: object
  - parent_id: object
  - project_id: object

In [11]:
table_profile("tasks_computed")

Table: tasks_computed
Shape: (628,466, 7)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - is_container: object
  - parent_id: object
  - project_id: object
  - planned_duration: object
  - elapsed_duration: object

In [12]:
table_profile("declarations")

Table: declarations
Shape: (4,446,669, 7)

Columns:
  - id: object
  - created_at: datetime64[ns, UTC]
  - date: object
  - durations: int64
  - source: object
  - user_id: object
  - task_id: object

In [13]:
table_profile("subscriptions")

Table: subscriptions
Shape: (2,838, 7)

Columns:
  - team_id: object
  - subscribe_at: datetime64[ns, UTC]
  - disabled_at: datetime64[ns, UTC]
  - status: object
  - offer: object
  - trial_start_at: datetime64[ns, UTC]
  - trial_end_at: datetime64[ns, UTC]

In [14]:
def header_profile(table_name, n=5):
    query = f'SELECT * FROM "{table_name}" LIMIT {n}'
    df = pd.read_sql(query, engine)
    return df

In [15]:
header_profile("users", 5)

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00:00,2024-08-18 00:00:00.189885+00:00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00:00,2024-08-25 00:00:00.079552+00:00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.884420+00:00,NaT,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00:00,NaT,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00:00,NaT,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [16]:
header_profile("teams", 5)

,id,created_at,deleted_at
0,0dae6fc0-5e50-40f5-a563-9ff3a924acc7,2023-04-19 09:53:26.653538+00:00,2024-07-23 00:00:00.080325+00:00
1,a09fdecc-9cb5-45bf-ac0f-82407ff0520e,2023-12-24 03:04:41.369719+00:00,2024-07-23 00:00:00.080325+00:00
2,15a5021a-4ca8-4058-93fc-d48eb288e262,2023-12-28 12:59:15.086754+00:00,2024-07-27 00:00:00.086003+00:00
3,b0acbb97-79c6-4009-a5cd-bed4f8fe3515,2024-02-23 12:23:14.626192+00:00,2024-08-22 00:00:00.108485+00:00
4,9d4ee2e9-0701-493b-ad36-a1c28b121ce4,2024-09-07 07:37:41.322453+00:00,NaT

In [17]:
header_profile("projects", 5)

,id,created_at,team_id
0,036ce646-3e35-4184-b13f-5f9f77b2a2bc,2024-02-07 06:08:30.869191+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
1,bcd4f818-a23a-4816-8b39-568cdd13c24e,2024-02-07 06:11:51.849856+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
2,1ee9281f-8fa1-4508-bcc7-0c541a519960,2024-02-07 06:12:15.748188+00:00,e6ef134a-284c-4008-8c95-fb5e75faa921
3,d96a67e4-2e35-4baf-a281-306f47a986ec,2023-11-15 19:56:45.089798+00:00,6227700f-b4c6-4465-b771-5081a8789a87
4,2fa1365c-f5a8-4557-a3ad-6ebfeae7ca97,2024-01-29 11:48:04.224718+00:00,504b8a66-fe1a-42e7-bad9-d026c3640ba2

In [18]:
header_profile("projects_computed", 5)

,id,created_at,team_id,planned_duration,elapsed_duration
0,a5d934fe-b9d2-4020-ae8c-f684c7b73d79,2024-02-21 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,0s
1,b446cbed-f3ec-4677-ba01-5de1b89796d2,2024-02-21 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,3h30m0s
2,806abfdf-3328-42e5-98f2-5c59b2c0870b,2024-02-24 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,6h0m0s
3,22797936-97ef-497e-8aec-e58c2ca542a2,2024-02-22 18:30:00+00:00,563a8fd7-b0e3-4a47-aaab-e24f57f30eed,0s,2h0m0s
4,3f95efc1-5edb-40ca-a76a-f35bd7abdb56,2024-02-21 18:30:00+00:00,eab347af-e533-41aa-99cd-02a2750d2b6a,0s,3h0m0s

In [19]:
header_profile("tasks", 5)

,id,created_at,is_container,parent_id,project_id
0,1ea825ce-97cf-4852-9288-0d81cf937391,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
1,ae179aa8-ebdf-457d-a86d-2af4d9f7b1e8,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
2,d8f19281-267d-4544-bf5e-6d24cdfe5320,2022-02-01 18:20:42.558161+00:00,f,bbee2ac3-f6aa-4cc9-b95d-cc39a50fbd40,b206bff4-6ebc-4b80-8b07-740d91be1007
3,ee4ba0a4-843c-4364-83c6-b548a6cb6ec7,2022-02-01 18:20:42.558161+00:00,f,ae9b3630-a2f4-4684-94f0-0ae7a65d27e8,b206bff4-6ebc-4b80-8b07-740d91be1007
4,be57f933-ca3d-4d14-a317-04ee78c042cc,2022-02-01 18:20:42.558161+00:00,f,ae9b3630-a2f4-4684-94f0-0ae7a65d27e8,b206bff4-6ebc-4b80-8b07-740d91be1007

In [20]:
header_profile("tasks_computed", 5)

,id,created_at,is_container,parent_id,project_id,planned_duration,elapsed_duration
0,e33ae6c4-bdae-47f0-b3b5-c640c0915a3b,2024-02-21 18:30:00+00:00,false,None,a5d934fe-b9d2-4020-ae8c-f684c7b73d79,0s,0s
1,7351af54-a08f-42d2-b00c-b012cd810912,2024-02-21 18:30:00+00:00,false,None,b446cbed-f3ec-4677-ba01-5de1b89796d2,0s,3h30m0s
2,b916baeb-85d6-4a19-a90c-5cbeb62bc6f9,2024-02-24 18:30:00+00:00,false,None,806abfdf-3328-42e5-98f2-5c59b2c0870b,0s,6h0m0s
3,b2b4b40c-a543-4a93-bdc0-ec89fd923e99,2024-02-24 18:30:00+00:00,false,None,806abfdf-3328-42e5-98f2-5c59b2c0870b,0s,0s
4,eae6977b-3b82-4279-ac37-26d0a886650f,2024-02-22 18:30:00+00:00,false,None,22797936-97ef-497e-8aec-e58c2ca542a2,0s,2h0m0s

In [21]:
header_profile("declarations", 5)

,id,created_at,date,durations,source,user_id,task_id
0,d0959001-d0b5-4db1-9060-8784ce18a45e,2023-07-20 16:27:27.418890+00:00,2023-07-20,8100000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,fcb25935-fa19-4729-88bb-6c6517da33f3
1,1f673cc8-af4b-479f-b1b1-d10d8f556455,2023-07-20 16:19:09.100997+00:00,2023-07-20,9000000000000,app,8525b67f-c5d4-494b-b010-f645bece73f4,26b908f6-1771-4da7-9b2e-fb9066af06fb
2,61a838e8-499e-4031-99f3-4bc7b4edd7e8,2023-07-20 16:27:35.834489+00:00,2023-07-20,5400000000000,app,355b940b-b7c2-46ae-9aae-059098688fee,3ce2459d-1441-4bbd-aa14-601f795806d4
3,2e8e7807-723a-433c-a4e1-06dfaebc24a5,2023-07-20 16:27:48.537053+00:00,2023-07-17,2700000000000,app,016030e1-e2fc-4a50-b2ab-3dfd72afe8bb,e215bb42-903b-43c7-bfa4-39aa90d5584c
4,d745827f-9cfc-42c6-996d-0eb52f5d52dc,2023-07-20 16:27:51.462235+00:00,2023-07-20,2700000000000,app,20544542-8f93-440a-bd6b-4b4a61d7e3de,3ce2459d-1441-4bbd-aa14-601f795806d4

In [22]:
header_profile("subscriptions", 5)

,team_id,subscribe_at,disabled_at,status,offer,trial_start_at,trial_end_at
0,40fbd3a5-a26f-40a0-9442-97f463846bfb,NaT,2024-09-16 17:42:15.404460+00:00,disabled,budget,2024-09-16 17:39:00.137959+00:00,2024-09-30 17:39:00.137959+00:00
1,76eed2db-c452-4e19-98ae-60b5cf99b46b,2024-05-27 14:31:51+00:00,NaT,active,budget,2024-05-12 21:31:11.178486+00:00,2024-05-26 21:31:11.178486+00:00
2,88592354-0ddb-4be7-95bf-14d0e5f47e70,NaT,2024-09-21 01:00:01.414810+00:00,disabled,budget,2024-09-06 13:29:42.567109+00:00,2024-09-20 13:29:42.567109+00:00
3,c9af2120-1b74-4ebb-8009-8b9224d4dace,2024-02-15 12:37:39+00:00,NaT,active,budget,2020-03-29 12:49:40.985137+00:00,2020-04-29 12:49:40.985137+00:00
4,6e894a69-4062-4a43-85f9-ed57ec0a01e8,NaT,2024-06-24 01:00:01.148573+00:00,disabled,budget,2024-06-09 12:28:16.371489+00:00,2024-06-23 12:28:16.371489+00:00

In [23]:
def uniqueness_profile(table_name, column):
    query = text(f"""
        SELECT
            COUNT(*) AS total_rows,
            COUNT(DISTINCT "{column}") AS unique_values,
            COUNT(*) - COUNT(DISTINCT "{column}") AS duplicate_count
        FROM "{table_name}";
    """)

    with engine.connect() as conn:
        result = conn.execute(query).mappings().one()

    return dict(result)

In [24]:
uniqueness_profile("users", "id")

{'total_rows': 20556, 'unique_values': 20556, 'duplicate_count': 0}

In [25]:
uniqueness_profile("teams", "id")

{'total_rows': 2838, 'unique_values': 2838, 'duplicate_count': 0}

In [26]:
uniqueness_profile("projects", "id")

{'total_rows': 71792, 'unique_values': 71792, 'duplicate_count': 0}

In [27]:
uniqueness_profile("projects_computed", "id")

{'total_rows': 61962, 'unique_values': 61962, 'duplicate_count': 0}

In [28]:
uniqueness_profile("tasks", "id")

{'total_rows': 717470, 'unique_values': 717470, 'duplicate_count': 0}

In [29]:
uniqueness_profile("tasks_computed", "id")

{'total_rows': 628466, 'unique_values': 628466, 'duplicate_count': 0}

In [30]:
uniqueness_profile("declarations", "id")

{'total_rows': 4446669, 'unique_values': 4446669, 'duplicate_count': 0}

In [31]:
uniqueness_profile("subscriptions", "team_id")

{'total_rows': 2838, 'unique_values': 2838, 'duplicate_count': 0}

In [32]:
query = """
SELECT
    tc.table_name AS child_table,
    kcu.column_name AS child_column,
    ccu.table_name AS parent_table,
    ccu.column_name AS parent_column
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
    AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
    AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
ORDER BY tc.table_name;
"""

relationships = pd.read_sql(query, engine)

relationships

         child_table child_column parent_table parent_column
0       declarations      user_id        users            id
1       declarations      task_id        tasks            id
2           projects      team_id        teams            id
3  projects_computed      team_id        teams            id
4      subscriptions      team_id        teams            id
5              tasks   project_id     projects            id
6     tasks_computed   project_id     projects            id
7              users      team_id        teams            id

In [36]:
def missing_profile(table_name):
    
    columns = pd.read_sql(
        f"""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = '{table_name}'
        ORDER BY ordinal_position;
        """,
        engine
    )

    results = []

    for column in columns["column_name"]:
        
        query = f"""
        SELECT
            '{table_name}' AS table_name,
            '{column}' AS column_name,
            COUNT(*) AS total_rows,
            COUNT(*) - COUNT("{column}") AS null_count,
            ROUND(
                (COUNT(*) - COUNT("{column}")) * 100.0 / COUNT(*),
                2
            ) AS null_percentage
        FROM "{table_name}";
        """

        results.append(pd.read_sql(query, engine))

    return pd.concat(results, ignore_index=True)

In [37]:
missing_profile("users")

  table_name column_name  total_rows  null_count  null_percentage
0      users          id       20556           0             0.00
1      users  created_at       20556           0             0.00
2      users  deleted_at       20556       11325            55.09
3      users     team_id       20556           0             0.00

In [38]:
missing_profile("teams")

  table_name column_name  total_rows  null_count  null_percentage
0      teams          id        2838           0             0.00
1      teams  created_at        2838           0             0.00
2      teams  deleted_at        2838         531            18.71

In [39]:
missing_profile("projects")

  table_name column_name  total_rows  null_count  null_percentage
0   projects          id       71792           0              0.0
1   projects  created_at       71792           0              0.0
2   projects     team_id       71792           0              0.0

In [40]:
missing_profile("projects_computed")

,table_name,column_name,total_rows,null_count,null_percentage
0,projects_computed,id,61962,0,0.0
1,projects_computed,created_at,61962,0,0.0
2,projects_computed,team_id,61962,0,0.0
3,projects_computed,planned_duration,61962,0,0.0
4,projects_computed,elapsed_duration,61962,0,0.0

In [41]:
missing_profile("tasks")

  table_name   column_name  total_rows  null_count  null_percentage
0      tasks            id      717470           0             0.00
1      tasks    created_at      717470           0             0.00
2      tasks  is_container      717470           0             0.00
3      tasks     parent_id      717470      297205            41.42
4      tasks    project_id      717470           0             0.00

In [42]:
missing_profile("tasks_computed")

       table_name       column_name  total_rows  null_count  null_percentage
0  tasks_computed                id      628466           0             0.00
1  tasks_computed        created_at      628466           0             0.00
2  tasks_computed      is_container      628466           0             0.00
3  tasks_computed         parent_id      628466      259704            41.32
4  tasks_computed        project_id      628466           0             0.00
5  tasks_computed  planned_duration      628466           0             0.00
6  tasks_computed  elapsed_duration      628466           0             0.00

In [43]:
missing_profile("declarations")

     table_name column_name  total_rows  null_count  null_percentage
0  declarations          id     4446669           0              0.0
1  declarations  created_at     4446669           0              0.0
2  declarations        date     4446669           0              0.0
3  declarations   durations     4446669           0              0.0
4  declarations      source     4446669           0              0.0
5  declarations     user_id     4446669           0              0.0
6  declarations     task_id     4446669           0              0.0

In [44]:
missing_profile("subscriptions")

      table_name     column_name  total_rows  null_count  null_percentage
0  subscriptions         team_id        2838           0             0.00
1  subscriptions    subscribe_at        2838        2248            79.21
2  subscriptions     disabled_at        2838         307            10.82
3  subscriptions          status        2838           0             0.00
4  subscriptions           offer        2838           0             0.00
5  subscriptions  trial_start_at        2838           0             0.00
6  subscriptions    trial_end_at        2838           0             0.00

In [52]:
query = """
SELECT
    table_name,
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
AND data_type IN ('date', 'timestamp', 'timestamp without time zone', 'timestamp with time zone')
ORDER BY table_name, ordinal_position;
"""

date_tables = pd.read_sql(query, engine)

results = []

for _, row in date_tables.iterrows():
    table_name = row["table_name"]
    column_name = row["column_name"]

    query = f"""
    SELECT
        '{table_name}' AS table_name,
        '{column_name}' AS column_name,
        MIN("{column_name}") AS min_date,
        MAX("{column_name}") AS max_date,
        COUNT(*) - COUNT("{column_name}") AS missing_dates
    FROM "{table_name}";
    """

    results.append(pd.read_sql(query, engine))

results_df = pd.concat(results, ignore_index=True)
results_df

,table_name,column_name,min_date,max_date,missing_dates
0,declarations,created_at,2017-12-11 12:57:59.821000+00:00,2024-10-10 14:29:25.575055+00:00,0
1,declarations,date,0001-01-01,2030-01-01,0
2,projects,created_at,2017-07-04 13:51:44+00:00,2024-10-10 14:29:04.609650+00:00,0
3,projects_computed,created_at,2017-07-03 18:30:00+00:00,2024-10-09 18:30:00+00:00,0
4,subscriptions,subscribe_at,2020-04-01 00:00:00+00:00,2024-10-09 10:22:58+00:00,2248
5,subscriptions,disabled_at,2020-04-30 09:00:56.397000+00:00,2024-10-10 01:00:08.780058+00:00,307
6,subscriptions,trial_start_at,2020-03-29 12:49:40.985137+00:00,2024-10-10 07:41:10.625296+00:00,0
7,subscriptions,trial_end_at,2020-04-29 12:49:40.985137+00:00,2024-10-24 07:41:10.625296+00:00,0
8,tasks,created_at,2017-07-04 13:51:44+00:00,2024-10-10 14:28:35.086893+00:00,0
9,tasks_computed,created_at,2017-07-03 18:30:00+00:00,2024-10-09 18:30:00+00:00,0
10,teams,created_at,2017-07-04 13:51:44+00:00,2024-10-10 07:41:10.626196+00:00,0
11,teams,deleted_at,2022-09-15 08:13:56.709031+00:00,2024-10-10 00:00:00.065686+00:00,531
12,users,created_at,2017-07-04 13:51:44+00:00,2024-10-10 07:41:10.876365+00:00,0
13,users,deleted_at,2022-09-15 08:13:56.709031+00:00,2024-10-10 00:00:00.065686+00:00,11325